# bitcoin.conf
server=1
network=regtest
rpcuser=olamosda
rpcpassword=cona.btc-Dao_5MoS7
rpcallowip=127.0.0.1
rpcmainport=8332
rpctestport=18332
rpcregport=18443

wallet.name=aowallet
btc.network=regtest
watchonly.wallet.name=btcnode_watchonly

# Add to bitcoin.conf
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
zmqpubhashblock=tcp://127.0.0.1:28334
zmqpubhashtx=tcp://127.0.0.1:28335